### ISSUE TITLE
Is it possible to go more in the stylization direction?

### ISSUE THREAD

**Issue by mrakgr** [zyxElsa/CAST_pytorch#4]
I've read the AdaIn paper, and get what it is about. I think if I did a convex combination of the original image latent vector and style image instead of outright replacing it one I could go in the direction of less stylization. But what about going the other way? Would doing something like weighting the original at -0.5 and the style at 1.5 actually work?

**Comment by mrakgr** [comment]
```py
    def forward(self, content, style, style_weight = 1.5):
        content_feats = self.encode(content)
        style_feats = self.encode(style)
        adain_feat = self.adain(content_feats, style_feats)
        return (1 - style_weight) * content_feats + style_weight * adain_feat
```

With the 1.5 setting here, it does end up being a good deal brighter than [the original](https://twitter.com/Ghostlike/status/1534477569302609920), but I am not sure if this is what I am going for. Still, the strokes themselves are different, so it might have some value. It is not just a simple change in brightness.
![room v4 denoised (great wave off kanagawa, 1 5 style weight)](https://user-images.githubusercontent.com/6266635/172598429-2d37932a-6d2e-4d6e-ab22-7526fbe57e02.png)

**Comment by surfingnirvana** [comment]
Where did you insert this code piece?

**Comment by mrakgr** [comment]
You can see it in my fork [here](https://github.com/mrakgr/CAST_pytorch/blob/4c90250976048bbe32d7a5ce5e4d925f474ae092/models/net.py#L119).

I put in some extra optimizations compared to the snipped above, but it's this here. The fork is behind compared to master though.
