### ISSUE TITLE
Where can i dowanload "style_vgg.pth". Is there a difference  with vgg_normalised.pt?

### ISSUE THREAD

**Issue by Jamie-Cheung** [zyxElsa/CAST_pytorch#7]

**Comment by zyxElsa** [comment]
"style_vgg.pth" is a pre-trained style classification model and the download link is now updated.
You can also train your own model on different dataset or other network structure.

**Comment by nobodypengium** [comment]
Solved.
You should put both ```style_vgg.pth``` and ```vgg_normalised.pt``` in folder ```models\```
It seems that ```vgg_normalised.pt``` provided in [AdaAttN](https://github.com/Huage001/AdaAttN) can be used, and you can download it from [here](https://drive.google.com/file/d/1BinnwM5AmIcVubr16tPTqxMjUCE8iu5M/view?usp=sharing).
@Jamie-Cheung

**Comment by zyxElsa** [comment]
Thanks. The download link of "vgg_normalised.pth"  is now updated.
